import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { ClipboardList, Filter, Calendar, CheckCircle2, Clock, FileText } from 'lucide-react';
import { Badge } from '../components/ui/badge';
import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
} from '../components/ui/card';
import { Select } from '../components/ui/select';
import { LoadingPage } from '../components/shared/Loading';
import { ErrorBanner } from '../components/shared/ErrorBanner';
import { EmptyState } from '../components/shared/EmptyState';
import { interviewSheetApi, type InterviewSheet } from '../api/interviewSheet';
import { projectsApi } from '../api/projects';
import type { Project, APIError } from '../api/types';

export const InterviewSheetsListPage: React.FC = () => {
  const navigate = useNavigate();
  const [sheets, setSheets] = useState<InterviewSheet[]>([]);
  const [projects, setProjects] = useState<Project[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<APIError | null>(null);
  const [selectedProject, setSelectedProject] = useState<string>('all');

  useEffect(() => {
    const fetchData = async () => {
      try {
        setLoading(true);
        setError(null);

        // Load projects and sheets in parallel
        const [projectsData, sheetsData] = await Promise.all([
          projectsApi.getAll(),
          interviewSheetApi.listAll()
        ]);

        setProjects(projectsData);
        setSheets(sheetsData.sheets);
      } catch (err) {
        setError(err as APIError);
      } finally {
        setLoading(false);
      }
    };

    fetchData();
  }, []);

  const handleProjectFilter = async (projectId: string) => {
    setSelectedProject(projectId);

    try {
      setLoading(true);
      const params = projectId !== 'all' ? { job_id: projectId } : undefined;
      const data = await interviewSheetApi.listAll(params);
      setSheets(data.sheets);
    } catch (err) {
      setError(err as APIError);
    } finally {
      setLoading(false);
    }
  };

  const getStatusBadge = (status: string) => {
    switch (status) {
      case 'completed':
        return <Badge variant="success"><CheckCircle2 className="mr-1 h-3 w-3" /> Completed</Badge>;
      case 'in_progress':
        return <Badge variant="default"><Clock className="mr-1 h-3 w-3" /> In progress</Badge>;
      case 'draft':
        return <Badge variant="secondary"><FileText className="mr-1 h-3 w-3" /> Draft</Badge>;
      default:
        return <Badge>{status}</Badge>;
    }
  };

  const formatDate = (dateStr: string) => {
    const date = new Date(dateStr);
    return date.toLocaleDateString('en-US', {
      day: '2-digit',
      month: '2-digit',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  if (loading) return <LoadingPage text="Loading interview sheets..." />;

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight flex items-center gap-2">
            <ClipboardList className="h-8 w-8" />
            Interview sheets
          </h1>
          <p className="text-muted-foreground mt-1">
            {sheets.length} sheet{sheets.length !== 1 ? 's' : ''} in total
          </p>
        </div>
      </div>

      {error && <ErrorBanner error={error} />}

      {/* Filters */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Filter className="h-5 w-5" />
            Filters
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="flex gap-4">
            <div className="flex-1">
              <label className="text-sm font-medium mb-2 block">Project</label>
              <Select
                value={selectedProject}
                onChange={(e) => handleProjectFilter(e.target.value)}
              >
                <option value="all">All projects</option>
                {projects.map((project) => (
                  <option key={project.id} value={project.id}>
                    {project.nom}
                  </option>
                ))}
              </Select>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Sheet list */}
      {sheets.length === 0 ? (
        <EmptyState
          icon={ClipboardList}
          title="No interview sheets yet"
          description="Interview sheets generated by matching runs will appear here."
        />
      ) : (
        <div className="grid gap-4">
          {sheets.map((sheet) => {
            const project = projects.find(p => p.id === sheet.job_id);

            return (
              <Card
                key={sheet.id}
                className="cursor-pointer hover:shadow-md transition-shadow"
                onClick={() => navigate(`/interviews/${sheet.id}`)}
              >
                <CardHeader>
                  <div className="flex items-start justify-between">
                    <div className="flex-1">
                      <CardTitle className="text-lg">
                        {sheet.candidate_id}
                      </CardTitle>
                      <CardDescription className="mt-1">
                        {project ? project.nom : sheet.job_id}
                      </CardDescription>
                    </div>
                    <div className="flex flex-col items-end gap-2">
                      {getStatusBadge(sheet.status)}
                      <div className="text-sm text-muted-foreground flex items-center gap-1">
                        <Calendar className="h-3 w-3" />
                        {formatDate(sheet.created_at)}
                      </div>
                    </div>
                  </div>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-2 gap-4 text-sm">
                    <div>
                      <span className="text-muted-foreground">Matching ID:</span>
                      <p className="font-mono text-xs mt-1">{sheet.matching_id}</p>
                    </div>
                    <div>
                      <span className="text-muted-foreground">Recruiter:</span>
                      <p className="mt-1">{sheet.interviewer_id}</p>
                    </div>
                  </div>
                  {sheet.completed_at && (
                    <div className="mt-4 pt-4 border-t">
                      <span className="text-sm text-muted-foreground">Completed on:</span>
                      <span className="text-sm font-medium">{formatDate(sheet.completed_at)}</span>
                    </div>
                  )}
                </CardContent>
              </Card>
            );
          })}
        </div>
      )}
    </div>
  );
};
